# Generated by Django 5.1.7 on 2025-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Africa Plan Foundation', max_length=100)),
                ('site_description', models.TextField(default='Empowering African youth through education and technology')),
                ('hero_title', models.CharField(default='Welcome to Africa Plan Foundation Test Platform', max_length=200)),
                ('hero_subtitle', models.TextField(default='Take assessments and improve your skills')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
                ('primary_color', models.CharField(default='#006400', max_length=20)),
                ('secondary_color', models.CharField(default='#00008B', max_length=20)),
                ('accent_color', models.CharField(default='#FFD700', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
