# Generated by Django 5.1.7 on 2025-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testcapture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcapture',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='testattempt',
            name='has_consented',
            field=models.BooleanField(default=False),
        ),
    ]
